data:
  MAX_LEN: 128
  KFTT: "data/kftt"

device: cuda
model:
  SP_MODEL: "src/translation/data/kftt_spm.model"
  SP_VOCAB: "src/translation/data/kftt_spm.vocab"
  VOCAB_SIZE: 16000
  MAX_LEN: 128
  BATCH_SIZE: 128
  EPOCHS: 10
  LEARNING_RATE: 0.0001
  IGNORE_INDEX: -100
  NUM_WORKER: 4
  

infer:
  checkpoints: ""